version: '3'

services:
  thereplay-contact:
    image: reg.synost.net/thereplay-contact:latest
    environment:
		  SMTP_HOST: "{{ SMTP_HOST }}"
		  SMTP_PORT: "{{ SMTP_PORT }}"
		  SMTP_USER: "{{ SMTP_USER }}"
		  SMTP_PASS: "{{ SMTP_PASS }}"
		  MAIL_TO: "{{ MAIL_TO }}"
		  MAIL_FROM: "{{ MAIL_FROM }}"
    ports:
      - 8080:3000